const translations = {

it:{producer:"Produttore",nutrition:"Informazioni nutrizionali",ingredients:"Ingredienti",nutritionText:"Valori medi per 100 ml di vino",parameter:"Parametro",value:"Valore",energy:"Energia",fat:"Grassi",saturated:"Acidi grassi saturi",carbs:"Carboidrati",sugars:"di cui zuccheri",protein:"Proteine",salt:"Sale",grape:"Uva biologica di nostra produzione",sulphites:"Conservante e antiossidante: Anidride Solforosa (E220)",stabilizer:"Stabilizzanti: nessuno",privacy:"Questo sito non utilizza cookie, analytics o sistemi di tracciamento.",organic:"BIOLOGICO",allergenTitle:"ALLERGENI",allergenText:"CONTIENE SOLFITI"},

en:{producer:"Producer",nutrition:"Nutrition Information",ingredients:"Ingredients",nutritionText:"Average values per 100 ml of wine",parameter:"Nutrient",value:"Value",energy:"Energy",fat:"Fat",saturated:"Saturated Fat",carbs:"Carbohydrates",sugars:"of which sugars",protein:"Protein",salt:"Salt",grape:"Organic grapes from our own production",sulphites:"Preservative and antioxidant: Sulphur dioxide (E220)",stabilizer:"Stabilizers: none",privacy:"This website does not use cookies, analytics or tracking systems.",organic:"ORGANIC",allergenTitle:"ALLERGENS",allergenText:"CONTAINS SULPHITES"},

fr:{producer:"Producteur",nutrition:"Informations nutritionnelles",ingredients:"Ingrédients",nutritionText:"Valeurs moyennes pour 100 ml de vin",parameter:"Paramètre",value:"Valeur",energy:"Énergie",fat:"Matières grasses",saturated:"Acides gras saturés",carbs:"Glucides",sugars:"dont sucres",protein:"Protéines",salt:"Sel",grape:"Raisins biologiques de notre production",sulphites:"Conservateur et antioxydant : Dioxyde de soufre (E220)",stabilizer:"Stabilisants : aucun",privacy:"Ce site n'utilise ni cookies, ni outils d'analyse, ni systèmes de suivi.",organic:"BIOLOGIQUE",allergenTitle:"ALLERGÈNES",allergenText:"CONTIENT DES SULFITES"},

de:{producer:"Hersteller",nutrition:"Nährwertangaben",ingredients:"Zutaten",nutritionText:"Durchschnittswerte pro 100 ml Wein",parameter:"Parameter",value:"Wert",energy:"Energie",fat:"Fett",saturated:"Gesättigte Fettsäuren",carbs:"Kohlenhydrate",sugars:"davon Zucker",protein:"Eiweiß",salt:"Salz",grape:"Biologisch erzeugte Trauben aus eigener Produktion",sulphites:"Konservierungsstoff und Antioxidationsmittel: Schwefeldioxid (E220)",stabilizer:"Stabilisatoren: keine",privacy:"Diese Website verwendet keine Cookies, Analysewerkzeuge oder Tracking-Systeme.",organic:"BIO",allergenTitle:"ALLERGENE",allergenText:"ENTHÄLT SULFITE"},

es:{producer:"Productor",nutrition:"Información nutricional",ingredients:"Ingredientes",nutritionText:"Valores medios por 100 ml de vino",parameter:"Parámetro",value:"Valor",energy:"Energía",fat:"Grasas",saturated:"Grasas saturadas",carbs:"Hidratos de carbono",sugars:"de los cuales azúcares",protein:"Proteínas",salt:"Sal",grape:"Uvas ecológicas de nuestra producción",sulphites:"Conservante y antioxidante: Dióxido de azufre (E220)",stabilizer:"Estabilizantes: ninguno",privacy:"Este sitio no utiliza cookies, herramientas analíticas ni sistemas de seguimiento.",organic:"ECOLÓGICO",allergenTitle:"ALÉRGENOS",allergenText:"CONTIENE SULFITOS"},

pt:{producer:"Produtor",nutrition:"Informação nutricional",ingredients:"Ingredientes",nutritionText:"Valores médios por 100 ml de vinho",parameter:"Parâmetro",value:"Valor",energy:"Energia",fat:"Gorduras",saturated:"Gorduras saturadas",carbs:"Hidratos de carbono",sugars:"dos quais açúcares",protein:"Proteínas",salt:"Sal",grape:"Uvas biológicas da nossa produção",sulphites:"Conservante e antioxidante: Dióxido de enxofre (E220)",stabilizer:"Estabilizantes: nenhum",privacy:"Este sítio não utiliza cookies, ferramentas analíticas nem sistemas de rastreamento.",organic:"BIOLÓGICO",allergenTitle:"ALERGÉNIOS",allergenText:"CONTÉM SULFITOS"},

nl:{producer:"Producent",nutrition:"Voedingsinformatie",ingredients:"Ingrediënten",nutritionText:"Gemiddelde waarden per 100 ml wijn",parameter:"Parameter",value:"Waarde",energy:"Energie",fat:"Vetten",saturated:"Verzadigde vetten",carbs:"Koolhydraten",sugars:"waarvan suikers",protein:"Eiwitten",salt:"Zout",grape:"Biologische druiven uit eigen productie",sulphites:"Conserveermiddel en antioxidant: Zwaveldioxide (E220)",stabilizer:"Stabilisatoren: geen",privacy:"Deze website gebruikt geen cookies, analysetools of trackingsystemen.",organic:"BIOLOGISCH",allergenTitle:"ALLERGENEN",allergenText:"BEVAT SULFIETEN"},

pl:{producer:"Producent",nutrition:"Informacje żywieniowe",ingredients:"Składniki",nutritionText:"Średnie wartości dla 100 ml wina",parameter:"Parametr",value:"Wartość",energy:"Energia",fat:"Tłuszcze",saturated:"Kwasy tłuszczowe nasycone",carbs:"Węglowodany",sugars:"w tym cukry",protein:"Białko",salt:"Sól",grape:"Ekologiczne winogrona z własnej produkcji",sulphites:"Konserwant i przeciwutleniacz: Dwutlenek siarki (E220)",stabilizer:"Stabilizatory: brak",privacy:"Ta strona nie używa plików cookie, narzędzi analitycznych ani systemów śledzenia.",organic:"EKOLOGICZNE",allergenTitle:"ALERGENY",allergenText:"ZAWIERA SIARCZYNY"},

cs:{producer:"Výrobce",nutrition:"Nutriční údaje",ingredients:"Složení",nutritionText:"Průměrné hodnoty na 100 ml vína",parameter:"Parametr",value:"Hodnota",energy:"Energie",fat:"Tuky",saturated:"Nasycené mastné kyseliny",carbs:"Sacharidy",sugars:"z toho cukry",protein:"Bílkoviny",salt:"Sůl",grape:"Bio hrozny z vlastní produkce",sulphites:"Konzervant a antioxidant: Oxid siřičitý (E220)",stabilizer:"Stabilizátory: žádné",privacy:"Tyto stránky nepoužívají cookies, analytické nástroje ani sledovací systémy.",organic:"EKOLOGICKÉ",allergenTitle:"ALERGENY",allergenText:"OBSAHUJE SIŘIČITANY"},

sk:{producer:"Výrobca",nutrition:"Výživové údaje",ingredients:"Zloženie",nutritionText:"Priemerné hodnoty na 100 ml vína",parameter:"Parameter",value:"Hodnota",energy:"Energia",fat:"Tuky",saturated:"Nasýtené mastné kyseliny",carbs:"Sacharidy",sugars:"z toho cukry",protein:"Bielkoviny",salt:"Soľ",grape:"Bio hrozno z vlastnej produkcie",sulphites:"Konzervačná látka a antioxidant: Oxid siričitý (E220)",stabilizer:"Stabilizátory: žiadne",privacy:"Táto stránka nepoužíva cookies, analytické nástroje ani sledovacie systémy.",organic:"EKOLOGICKÉ",allergenTitle:"ALERGÉNY",allergenText:"OBSAHUJE SIRIČITANY"},

sl:{producer:"Proizvajalec",nutrition:"Hranilne vrednosti",ingredients:"Sestavine",nutritionText:"Povprečne vrednosti na 100 ml vina",parameter:"Parameter",value:"Vrednost",energy:"Energija",fat:"Maščobe",saturated:"Nasičene maščobe",carbs:"Ogljikovi hidrati",sugars:"od tega sladkorji",protein:"Beljakovine",salt:"Sol",grape:"Ekološko grozdje iz lastne pridelave",sulphites:"Konzervans in antioksidant: Žveplov dioksid (E220)",stabilizer:"Stabilizatorji: brez",privacy:"Ta spletna stran ne uporablja piškotkov, analitičnih orodij ali sistemov za sledenje.",organic:"EKOLOŠKO",allergenTitle:"ALERGENI",allergenText:"VSEBUJE SULFITE"},

hr:{producer:"Proizvođač",nutrition:"Nutritivne vrijednosti",ingredients:"Sastojci",nutritionText:"Prosječne vrijednosti na 100 ml vina",parameter:"Parametar",value:"Vrijednost",energy:"Energija",fat:"Masti",saturated:"Zasićene masne kiseline",carbs:"Ugljikohidrati",sugars:"od toga šećeri",protein:"Proteini",salt:"Sol",grape:"Ekološko grožđe iz vlastite proizvodnje",sulphites:"Konzervans i antioksidans: Sumporov dioksid (E220)",stabilizer:"Stabilizatori: nema",privacy:"Ova web stranica ne koristi kolačiće, analitičke alate ni sustave praćenja.",organic:"EKOLOŠKO",allergenTitle:"ALERGENI",allergenText:"SADRŽI SULFITE"},

hu:{producer:"Gyártó",nutrition:"Tápérték adatok",ingredients:"Összetevők",nutritionText:"Átlagos értékek 100 ml borra",parameter:"Paraméter",value:"Érték",energy:"Energia",fat:"Zsír",saturated:"Telített zsírsavak",carbs:"Szénhidrát",sugars:"ebből cukor",protein:"Fehérje",salt:"Só",grape:"Saját termesztésű bio szőlő",sulphites:"Tartósítószer és antioxidáns: Kén-dioxid (E220)",stabilizer:"Stabilizátorok: nincs",privacy:"Ez a weboldal nem használ sütiket, analitikai vagy nyomkövető rendszereket.",organic:"BIO",allergenTitle:"ALLERGÉNEK",allergenText:"SZULFITOKAT TARTALMAZ"},

ro:{producer:"Producător",nutrition:"Informații nutriționale",ingredients:"Ingrediente",nutritionText:"Valori medii pentru 100 ml vin",parameter:"Parametru",value:"Valoare",energy:"Energie",fat:"Grăsimi",saturated:"Acizi grași saturați",carbs:"Carbohidrați",sugars:"din care zaharuri",protein:"Proteine",salt:"Sare",grape:"Struguri ecologici din producția proprie",sulphites:"Conservant și antioxidant: Dioxid de sulf (E220)",stabilizer:"Stabilizatori: niciunul",privacy:"Acest site nu utilizează cookie-uri, instrumente analitice sau sisteme de urmărire.",organic:"ECOLOGIC",allergenTitle:"ALERGENI",allergenText:"CONȚINE SULFIȚI"},

bg:{producer:"Производител",nutrition:"Хранителни стойности",ingredients:"Съставки",nutritionText:"Средни стойности за 100 ml вино",parameter:"Параметър",value:"Стойност",energy:"Енергия",fat:"Мазнини",saturated:"Наситени мастни киселини",carbs:"Въглеводи",sugars:"от тях захари",protein:"Протеини",salt:"Сол",grape:"Биологично грозде от собствено производство",sulphites:"Консервант и антиоксидант: Серен диоксид (E220)",stabilizer:"Стабилизатори: няма",privacy:"Този сайт не използва бисквитки, аналитични инструменти или системи за проследяване.",organic:"БИОЛОГИЧНО",allergenTitle:"АЛЕРГЕНИ",allergenText:"СЪДЪРЖА СУЛФИТИ"},

el:{producer:"Παραγωγός",nutrition:"Διατροφικές πληροφορίες",ingredients:"Συστατικά",nutritionText:"Μέσες τιμές ανά 100 ml κρασιού",parameter:"Παράμετρος",value:"Τιμή",energy:"Ενέργεια",fat:"Λίπη",saturated:"Κορεσμένα λιπαρά οξέα",carbs:"Υδατάνθρακες",sugars:"εκ των οποίων ζάχαρα",protein:"Πρωτεΐνες",salt:"Αλάτι",grape:"Βιολογικά σταφύλια από δική μας παραγωγή",sulphites:"Συντηρητικό και αντιοξειδωτικό: Διοξείδιο του θείου (E220)",stabilizer:"Σταθεροποιητικές ουσίες: καμία",privacy:"Αυτός ο ιστότοπος δεν χρησιμοποιεί cookies, αναλυτικά εργαλεία ή συστήματα παρακολούθησης.",organic:"ΒΙΟΛΟΓΙΚΟ",allergenTitle:"ΑΛΛΕΡΓΙΟΓΟΝΑ",allergenText:"ΠΕΡΙΕΧΕΙ ΘΕΙΩΔΗ"},

sv:{producer:"Producent",nutrition:"Näringsinformation",ingredients:"Ingredienser",nutritionText:"Genomsnittliga värden per 100 ml vin",parameter:"Parameter",value:"Värde",energy:"Energi",fat:"Fett",saturated:"Mättade fettsyror",carbs:"Kolhydrater",sugars:"varav socker",protein:"Protein",salt:"Salt",grape:"Ekologiska druvor från egen produktion",sulphites:"Konserveringsmedel och antioxidant: Svaveldioxid (E220)",stabilizer:"Stabiliseringsmedel: inga",privacy:"Den här webbplatsen använder inga cookies, analysverktyg eller spårningssystem.",organic:"EKOLOGISK",allergenTitle:"ALLERGENER",allergenText:"INNEHÅLLER SULFITER"},

da:{producer:"Producent",nutrition:"Næringsindhold",ingredients:"Ingredienser",nutritionText:"Gennemsnitlige værdier pr. 100 ml vin",parameter:"Parameter",value:"Værdi",energy:"Energi",fat:"Fedt",saturated:"Mættede fedtsyrer",carbs:"Kulhydrater",sugars:"heraf sukker",protein:"Protein",salt:"Salt",grape:"Økologiske druer fra egen produktion",sulphites:"Konserveringsmiddel og antioxidationsmiddel: Svovldioxid (E220)",stabilizer:"Stabilizatorer: ingen",privacy:"Dette website bruger ikke cookies, analysesværktøjer eller sporingssystemer.",organic:"ØKOLOGISK",allergenTitle:"ALLERGENER",allergenText:"INDEHOLDER SULFITTER"},

fi:{producer:"Valmistaja",nutrition:"Ravintoarvot",ingredients:"Ainesosat",nutritionText:"Keskimääräiset arvot / 100 ml viiniä",parameter:"Parametri",value:"Arvo",energy:"Energia",fat:"Rasva",saturated:"Tyydyttyneet rasvahapot",carbs:"Hiilihydraatit",sugars:"joista sokeria",protein:"Proteiini",salt:"Suola",grape:"Ekologisia viinirypäleitä omasta tuotannosta",sulphites:"Säilöntäaine ja antioksidantti: Rikkidioksidi (E220)",stabilizer:"Stabilointiaineet: ei mitään",privacy:"Tämä sivusto ei käytä evästeitä, analytiikkaa tai seurantajärjestelmiä.",organic:"BIOLOGINEN",allergenTitle:"ALLERGEENIT",allergenText:"SISÄLTÄÄ SULFIITTEJA"},

et:{producer:"Tootja",nutrition:"Toitumisalane teave",ingredients:"Koostisosad",nutritionText:"Keskmised väärtused 100 ml veini kohta",parameter:"Parameeter",value:"Väärtus",energy:"Energia",fat:"Rasv",saturated:"Küllastunud rasvhapped",carbs:"Süsivesikud",sugars:"millest suhkruid",protein:"Valgud",salt:"Sool",grape:"Ökoloogilised viinamarjad oma tootmisest",sulphites:"Konservant ja antioksüdant: Rikkdioksiid (E220)",stabilizer:"Stabilisaatorid: puuduvad",privacy:"See veebisait ei kasuta küpsiseid, analüüsivahendeid ega jälgimissüsteeme.",organic:"ORGANIC",allergenTitle:"ALLERGEENID",allergenText:"SISALDAB SULFITEID"},

lv:{producer:"Ražotājs",nutrition:"Uzturvērtība",ingredients:"Sastāvdaļas",nutritionText:"Vidējās vērtības uz 100 ml vīna",parameter:"Parametrs",value:"Vērtība",energy:"Enerģija",fat:"Tauki",saturated:"Piesātinātās taukskābes",carbs:"Ogļhidrāti",sugars:"no tā cukuri",protein:"Olbaltumvielas",salt:"Sāls",grape:"Bioloģiskie vīnogas no savas ražošanas",sulphites:"Konservants un antioksidants: Sēra dioksīds (E220)",stabilizer:"Stabilizatori: nav",privacy:"Šī vietne neizmanto sīkfailus, analītiskos rīkus vai izsekošanas sistēmas.",organic:"BIOLOĢISKA",allergenTitle:"ALERĢĒNI",allergenText:"SATUR SULFĪTUS"},

lt:{producer:"Gamintojas",nutrition:"Maistinė vertė",ingredients:"Sudedamosios dalys",nutritionText:"Vidutinės vertės 100 ml vyno",parameter:"Parametras",value:"Vertė",energy:"Energija",fat:"Riebalai",saturated:"Sočiosios riebalų rūgštys",carbs:"Angliavandeniai",sugars:"iš to cukraus",protein:"Baltymai",salt:"Druska",grape:"Ekologiški vynuogės iš savo produkcijos",sulphites:"Konservantas ir antioksidantas: Sieros dioksidas (E220)",stabilizer:"Stabilizatoriai: nėra",privacy:"Ši svetainė nenaudoja slapukų, analizės įrankių ar sekimo sistemų.",organic:"EKOLOGIŠKAS",allergenTitle:"ALERGENAI",allergenText:"SUDĖTYJE YRA SULFITŲ"},

mt:{producer:"Produttur",nutrition:"Informazzjoni Nutrizzjonali",ingredients:"Ingredjenti",nutritionText:"Valuri medji għal kull 100 ml inbid",parameter:"Parametru",value:"Valur",energy:"Enerġija",fat:"Xaħmijiet",saturated:"Aċidi grassi saturati",carbs:"Karboidrati",sugars:"minn dawn il-zokkor",protein:"Proteini",salt:"Miel",grape:"Għeneb organiku mill-produzzjoni tagħna",sulphites:"Konservant u anti-ossidant: Dijossidu tal-kubrit (E220)",stabilizer:"Stabilizzanti: l-ebda",privacy:"Dan is-sit ma juża cookies, għodod analitiċi jew sistemi ta’ traċċar.",organic:"BIOLOĠIKU",allergenTitle:"ALLERĠENI",allergenText:"FIH SULFITI"},

ga:{producer:"Táirgeoir",nutrition:"Eolas Cothaithe",ingredients:"Comhábhair",nutritionText:"Meánluachanna in aghaidh 100 ml fíona",parameter:"Paraiméadar",value:"Luach",energy:"Fuinneamh",fat:"Saill",saturated:"Saill sáithithe",carbs:"Carbaihiodráití",sugars:"fúithi siúcra",protein:"Próitéin",salt:"Salann",grape:"Fíonchaora orgánacha as ár dtáirgeadh féin",sulphites:"Leasachán agus frithocsaídeoir: Dé-ocsaíd sulfair (E220)",stabilizer:"Stabilizers: none",privacy:"Ní úsáideann an suíomh seo fianáin, uirlisí anailíse ná córais rianaithe.",organic:"ORGÁNACH",allergenTitle:"AERGHÉINN",allergenText:"TÁ SULFAITÍ ANN"}

};

